"""Add topic fields to practice sessions

Revision ID: 115c04c30981
Revises: ebb676a018a8
Create Date: 2026-08-15 00:24:04.367425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '115c04c30981'
down_revision: Union[str, Sequence[str], None] = 'ebb676a018a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_sessions', sa.Column('topic_title', sa.String(), nullable=True))
    op.add_column('practice_sessions', sa.Column('topic_category', sa.String(), nullable=True))
    op.add_column('practice_sessions', sa.Column('topic_difficulty', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practice_sessions', 'topic_difficulty')
    op.drop_column('practice_sessions', 'topic_category')
    op.drop_column('practice_sessions', 'topic_title')
    # ### end Alembic commands ###
